// Code generated by ent, DO NOT EDIT.

package openaievalrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaievalrun type in the database.
	Label = "open_ai_eval_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTestType holds the string denoting the test_type field in the database.
	FieldTestType = "test_type"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldReasoningEffort holds the string denoting the reasoning_effort field in the database.
	FieldReasoningEffort = "reasoning_effort"
	// FieldDataVersion holds the string denoting the data_version field in the database.
	FieldDataVersion = "data_version"
	// FieldBaselineVersion holds the string denoting the baseline_version field in the database.
	FieldBaselineVersion = "baseline_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldSamples holds the string denoting the samples field in the database.
	FieldSamples = "samples"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCostEstimateUsd holds the string denoting the cost_estimate_usd field in the database.
	FieldCostEstimateUsd = "cost_estimate_usd"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldTriggeredBy holds the string denoting the triggered_by field in the database.
	FieldTriggeredBy = "triggered_by"
	// FieldTriggerSource holds the string denoting the trigger_source field in the database.
	FieldTriggerSource = "trigger_source"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRetentionUntil holds the string denoting the retention_until field in the database.
	FieldRetentionUntil = "retention_until"
	// Table holds the table name of the openaievalrun in the database.
	Table = "openai_eval_runs"
)

// Columns holds all SQL columns for openaievalrun fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldTestType,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldReasoningEffort,
	FieldDataVersion,
	FieldBaselineVersion,
	FieldStatus,
	FieldOutcome,
	FieldSamples,
	FieldRequestCount,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCostEstimateUsd,
	FieldDurationMs,
	FieldStartedAt,
	FieldFinishedAt,
	FieldTriggeredBy,
	FieldTriggerSource,
	FieldErrorCode,
	FieldCreatedAt,
	FieldRetentionUntil,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TestTypeValidator is a validator for the "test_type" field. It is called by the builders before save.
	TestTypeValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// DefaultUpstreamModel holds the default value on creation for the "upstream_model" field.
	DefaultUpstreamModel string
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultReasoningEffort holds the default value on creation for the "reasoning_effort" field.
	DefaultReasoningEffort string
	// ReasoningEffortValidator is a validator for the "reasoning_effort" field. It is called by the builders before save.
	ReasoningEffortValidator func(string) error
	// DataVersionValidator is a validator for the "data_version" field. It is called by the builders before save.
	DataVersionValidator func(string) error
	// DefaultBaselineVersion holds the default value on creation for the "baseline_version" field.
	DefaultBaselineVersion string
	// BaselineVersionValidator is a validator for the "baseline_version" field. It is called by the builders before save.
	BaselineVersionValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultOutcome holds the default value on creation for the "outcome" field.
	DefaultOutcome map[string]interface{}
	// DefaultSamples holds the default value on creation for the "samples" field.
	DefaultSamples []map[string]interface{}
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
	// DefaultTriggeredBy holds the default value on creation for the "triggered_by" field.
	DefaultTriggeredBy int64
	// TriggerSourceValidator is a validator for the "trigger_source" field. It is called by the builders before save.
	TriggerSourceValidator func(string) error
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAIEvalRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTestType orders the results by the test_type field.
func ByTestType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTestType, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByReasoningEffort orders the results by the reasoning_effort field.
func ByReasoningEffort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningEffort, opts...).ToFunc()
}

// ByDataVersion orders the results by the data_version field.
func ByDataVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataVersion, opts...).ToFunc()
}

// ByBaselineVersion orders the results by the baseline_version field.
func ByBaselineVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCostEstimateUsd orders the results by the cost_estimate_usd field.
func ByCostEstimateUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostEstimateUsd, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByTriggeredBy orders the results by the triggered_by field.
func ByTriggeredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredBy, opts...).ToFunc()
}

// ByTriggerSource orders the results by the trigger_source field.
func ByTriggerSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerSource, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRetentionUntil orders the results by the retention_until field.
func ByRetentionUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetentionUntil, opts...).ToFunc()
}
