// Code generated by ent, DO NOT EDIT.

package openaievalrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldAccountID, v))
}

// TestType applies equality check predicate on the "test_type" field. It's identical to TestTypeEQ.
func TestType(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTestType, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRequestedModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldUpstreamModel, v))
}

// ReasoningEffort applies equality check predicate on the "reasoning_effort" field. It's identical to ReasoningEffortEQ.
func ReasoningEffort(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldReasoningEffort, v))
}

// DataVersion applies equality check predicate on the "data_version" field. It's identical to DataVersionEQ.
func DataVersion(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldDataVersion, v))
}

// BaselineVersion applies equality check predicate on the "baseline_version" field. It's identical to BaselineVersionEQ.
func BaselineVersion(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldBaselineVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldStatus, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRequestCount, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldOutputTokens, v))
}

// CostEstimateUsd applies equality check predicate on the "cost_estimate_usd" field. It's identical to CostEstimateUsdEQ.
func CostEstimateUsd(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldCostEstimateUsd, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldDurationMs, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldFinishedAt, v))
}

// TriggeredBy applies equality check predicate on the "triggered_by" field. It's identical to TriggeredByEQ.
func TriggeredBy(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTriggeredBy, v))
}

// TriggerSource applies equality check predicate on the "trigger_source" field. It's identical to TriggerSourceEQ.
func TriggerSource(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTriggerSource, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldErrorCode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldCreatedAt, v))
}

// RetentionUntil applies equality check predicate on the "retention_until" field. It's identical to RetentionUntilEQ.
func RetentionUntil(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRetentionUntil, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldAccountID, v))
}

// TestTypeEQ applies the EQ predicate on the "test_type" field.
func TestTypeEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTestType, v))
}

// TestTypeNEQ applies the NEQ predicate on the "test_type" field.
func TestTypeNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldTestType, v))
}

// TestTypeIn applies the In predicate on the "test_type" field.
func TestTypeIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldTestType, vs...))
}

// TestTypeNotIn applies the NotIn predicate on the "test_type" field.
func TestTypeNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldTestType, vs...))
}

// TestTypeGT applies the GT predicate on the "test_type" field.
func TestTypeGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldTestType, v))
}

// TestTypeGTE applies the GTE predicate on the "test_type" field.
func TestTypeGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldTestType, v))
}

// TestTypeLT applies the LT predicate on the "test_type" field.
func TestTypeLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldTestType, v))
}

// TestTypeLTE applies the LTE predicate on the "test_type" field.
func TestTypeLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldTestType, v))
}

// TestTypeContains applies the Contains predicate on the "test_type" field.
func TestTypeContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldTestType, v))
}

// TestTypeHasPrefix applies the HasPrefix predicate on the "test_type" field.
func TestTypeHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldTestType, v))
}

// TestTypeHasSuffix applies the HasSuffix predicate on the "test_type" field.
func TestTypeHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldTestType, v))
}

// TestTypeEqualFold applies the EqualFold predicate on the "test_type" field.
func TestTypeEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldTestType, v))
}

// TestTypeContainsFold applies the ContainsFold predicate on the "test_type" field.
func TestTypeContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldTestType, v))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldRequestedModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// ReasoningEffortEQ applies the EQ predicate on the "reasoning_effort" field.
func ReasoningEffortEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldReasoningEffort, v))
}

// ReasoningEffortNEQ applies the NEQ predicate on the "reasoning_effort" field.
func ReasoningEffortNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldReasoningEffort, v))
}

// ReasoningEffortIn applies the In predicate on the "reasoning_effort" field.
func ReasoningEffortIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortNotIn applies the NotIn predicate on the "reasoning_effort" field.
func ReasoningEffortNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortGT applies the GT predicate on the "reasoning_effort" field.
func ReasoningEffortGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldReasoningEffort, v))
}

// ReasoningEffortGTE applies the GTE predicate on the "reasoning_effort" field.
func ReasoningEffortGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldReasoningEffort, v))
}

// ReasoningEffortLT applies the LT predicate on the "reasoning_effort" field.
func ReasoningEffortLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldReasoningEffort, v))
}

// ReasoningEffortLTE applies the LTE predicate on the "reasoning_effort" field.
func ReasoningEffortLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldReasoningEffort, v))
}

// ReasoningEffortContains applies the Contains predicate on the "reasoning_effort" field.
func ReasoningEffortContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldReasoningEffort, v))
}

// ReasoningEffortHasPrefix applies the HasPrefix predicate on the "reasoning_effort" field.
func ReasoningEffortHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldReasoningEffort, v))
}

// ReasoningEffortHasSuffix applies the HasSuffix predicate on the "reasoning_effort" field.
func ReasoningEffortHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldReasoningEffort, v))
}

// ReasoningEffortEqualFold applies the EqualFold predicate on the "reasoning_effort" field.
func ReasoningEffortEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldReasoningEffort, v))
}

// ReasoningEffortContainsFold applies the ContainsFold predicate on the "reasoning_effort" field.
func ReasoningEffortContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldReasoningEffort, v))
}

// DataVersionEQ applies the EQ predicate on the "data_version" field.
func DataVersionEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldDataVersion, v))
}

// DataVersionNEQ applies the NEQ predicate on the "data_version" field.
func DataVersionNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldDataVersion, v))
}

// DataVersionIn applies the In predicate on the "data_version" field.
func DataVersionIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldDataVersion, vs...))
}

// DataVersionNotIn applies the NotIn predicate on the "data_version" field.
func DataVersionNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldDataVersion, vs...))
}

// DataVersionGT applies the GT predicate on the "data_version" field.
func DataVersionGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldDataVersion, v))
}

// DataVersionGTE applies the GTE predicate on the "data_version" field.
func DataVersionGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldDataVersion, v))
}

// DataVersionLT applies the LT predicate on the "data_version" field.
func DataVersionLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldDataVersion, v))
}

// DataVersionLTE applies the LTE predicate on the "data_version" field.
func DataVersionLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldDataVersion, v))
}

// DataVersionContains applies the Contains predicate on the "data_version" field.
func DataVersionContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldDataVersion, v))
}

// DataVersionHasPrefix applies the HasPrefix predicate on the "data_version" field.
func DataVersionHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldDataVersion, v))
}

// DataVersionHasSuffix applies the HasSuffix predicate on the "data_version" field.
func DataVersionHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldDataVersion, v))
}

// DataVersionEqualFold applies the EqualFold predicate on the "data_version" field.
func DataVersionEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldDataVersion, v))
}

// DataVersionContainsFold applies the ContainsFold predicate on the "data_version" field.
func DataVersionContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldDataVersion, v))
}

// BaselineVersionEQ applies the EQ predicate on the "baseline_version" field.
func BaselineVersionEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldBaselineVersion, v))
}

// BaselineVersionNEQ applies the NEQ predicate on the "baseline_version" field.
func BaselineVersionNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldBaselineVersion, v))
}

// BaselineVersionIn applies the In predicate on the "baseline_version" field.
func BaselineVersionIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldBaselineVersion, vs...))
}

// BaselineVersionNotIn applies the NotIn predicate on the "baseline_version" field.
func BaselineVersionNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldBaselineVersion, vs...))
}

// BaselineVersionGT applies the GT predicate on the "baseline_version" field.
func BaselineVersionGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldBaselineVersion, v))
}

// BaselineVersionGTE applies the GTE predicate on the "baseline_version" field.
func BaselineVersionGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldBaselineVersion, v))
}

// BaselineVersionLT applies the LT predicate on the "baseline_version" field.
func BaselineVersionLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldBaselineVersion, v))
}

// BaselineVersionLTE applies the LTE predicate on the "baseline_version" field.
func BaselineVersionLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldBaselineVersion, v))
}

// BaselineVersionContains applies the Contains predicate on the "baseline_version" field.
func BaselineVersionContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldBaselineVersion, v))
}

// BaselineVersionHasPrefix applies the HasPrefix predicate on the "baseline_version" field.
func BaselineVersionHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldBaselineVersion, v))
}

// BaselineVersionHasSuffix applies the HasSuffix predicate on the "baseline_version" field.
func BaselineVersionHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldBaselineVersion, v))
}

// BaselineVersionEqualFold applies the EqualFold predicate on the "baseline_version" field.
func BaselineVersionEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldBaselineVersion, v))
}

// BaselineVersionContainsFold applies the ContainsFold predicate on the "baseline_version" field.
func BaselineVersionContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldBaselineVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldStatus, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldRequestCount, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldOutputTokens, v))
}

// CostEstimateUsdEQ applies the EQ predicate on the "cost_estimate_usd" field.
func CostEstimateUsdEQ(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldCostEstimateUsd, v))
}

// CostEstimateUsdNEQ applies the NEQ predicate on the "cost_estimate_usd" field.
func CostEstimateUsdNEQ(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldCostEstimateUsd, v))
}

// CostEstimateUsdIn applies the In predicate on the "cost_estimate_usd" field.
func CostEstimateUsdIn(vs ...float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldCostEstimateUsd, vs...))
}

// CostEstimateUsdNotIn applies the NotIn predicate on the "cost_estimate_usd" field.
func CostEstimateUsdNotIn(vs ...float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldCostEstimateUsd, vs...))
}

// CostEstimateUsdGT applies the GT predicate on the "cost_estimate_usd" field.
func CostEstimateUsdGT(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldCostEstimateUsd, v))
}

// CostEstimateUsdGTE applies the GTE predicate on the "cost_estimate_usd" field.
func CostEstimateUsdGTE(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldCostEstimateUsd, v))
}

// CostEstimateUsdLT applies the LT predicate on the "cost_estimate_usd" field.
func CostEstimateUsdLT(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldCostEstimateUsd, v))
}

// CostEstimateUsdLTE applies the LTE predicate on the "cost_estimate_usd" field.
func CostEstimateUsdLTE(v float64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldCostEstimateUsd, v))
}

// CostEstimateUsdIsNil applies the IsNil predicate on the "cost_estimate_usd" field.
func CostEstimateUsdIsNil() predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIsNull(FieldCostEstimateUsd))
}

// CostEstimateUsdNotNil applies the NotNil predicate on the "cost_estimate_usd" field.
func CostEstimateUsdNotNil() predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotNull(FieldCostEstimateUsd))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldDurationMs, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotNull(FieldFinishedAt))
}

// TriggeredByEQ applies the EQ predicate on the "triggered_by" field.
func TriggeredByEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTriggeredBy, v))
}

// TriggeredByNEQ applies the NEQ predicate on the "triggered_by" field.
func TriggeredByNEQ(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldTriggeredBy, v))
}

// TriggeredByIn applies the In predicate on the "triggered_by" field.
func TriggeredByIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldTriggeredBy, vs...))
}

// TriggeredByNotIn applies the NotIn predicate on the "triggered_by" field.
func TriggeredByNotIn(vs ...int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldTriggeredBy, vs...))
}

// TriggeredByGT applies the GT predicate on the "triggered_by" field.
func TriggeredByGT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldTriggeredBy, v))
}

// TriggeredByGTE applies the GTE predicate on the "triggered_by" field.
func TriggeredByGTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldTriggeredBy, v))
}

// TriggeredByLT applies the LT predicate on the "triggered_by" field.
func TriggeredByLT(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldTriggeredBy, v))
}

// TriggeredByLTE applies the LTE predicate on the "triggered_by" field.
func TriggeredByLTE(v int64) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldTriggeredBy, v))
}

// TriggerSourceEQ applies the EQ predicate on the "trigger_source" field.
func TriggerSourceEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldTriggerSource, v))
}

// TriggerSourceNEQ applies the NEQ predicate on the "trigger_source" field.
func TriggerSourceNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldTriggerSource, v))
}

// TriggerSourceIn applies the In predicate on the "trigger_source" field.
func TriggerSourceIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldTriggerSource, vs...))
}

// TriggerSourceNotIn applies the NotIn predicate on the "trigger_source" field.
func TriggerSourceNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldTriggerSource, vs...))
}

// TriggerSourceGT applies the GT predicate on the "trigger_source" field.
func TriggerSourceGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldTriggerSource, v))
}

// TriggerSourceGTE applies the GTE predicate on the "trigger_source" field.
func TriggerSourceGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldTriggerSource, v))
}

// TriggerSourceLT applies the LT predicate on the "trigger_source" field.
func TriggerSourceLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldTriggerSource, v))
}

// TriggerSourceLTE applies the LTE predicate on the "trigger_source" field.
func TriggerSourceLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldTriggerSource, v))
}

// TriggerSourceContains applies the Contains predicate on the "trigger_source" field.
func TriggerSourceContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldTriggerSource, v))
}

// TriggerSourceHasPrefix applies the HasPrefix predicate on the "trigger_source" field.
func TriggerSourceHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldTriggerSource, v))
}

// TriggerSourceHasSuffix applies the HasSuffix predicate on the "trigger_source" field.
func TriggerSourceHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldTriggerSource, v))
}

// TriggerSourceEqualFold applies the EqualFold predicate on the "trigger_source" field.
func TriggerSourceEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldTriggerSource, v))
}

// TriggerSourceContainsFold applies the ContainsFold predicate on the "trigger_source" field.
func TriggerSourceContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldTriggerSource, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldContainsFold(FieldErrorCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldCreatedAt, v))
}

// RetentionUntilEQ applies the EQ predicate on the "retention_until" field.
func RetentionUntilEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldEQ(FieldRetentionUntil, v))
}

// RetentionUntilNEQ applies the NEQ predicate on the "retention_until" field.
func RetentionUntilNEQ(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNEQ(FieldRetentionUntil, v))
}

// RetentionUntilIn applies the In predicate on the "retention_until" field.
func RetentionUntilIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldIn(FieldRetentionUntil, vs...))
}

// RetentionUntilNotIn applies the NotIn predicate on the "retention_until" field.
func RetentionUntilNotIn(vs ...time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldNotIn(FieldRetentionUntil, vs...))
}

// RetentionUntilGT applies the GT predicate on the "retention_until" field.
func RetentionUntilGT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGT(FieldRetentionUntil, v))
}

// RetentionUntilGTE applies the GTE predicate on the "retention_until" field.
func RetentionUntilGTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldGTE(FieldRetentionUntil, v))
}

// RetentionUntilLT applies the LT predicate on the "retention_until" field.
func RetentionUntilLT(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLT(FieldRetentionUntil, v))
}

// RetentionUntilLTE applies the LTE predicate on the "retention_until" field.
func RetentionUntilLTE(v time.Time) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.FieldLTE(FieldRetentionUntil, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIEvalRun) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIEvalRun) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIEvalRun) predicate.OpenAIEvalRun {
	return predicate.OpenAIEvalRun(sql.NotPredicates(p))
}
