// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaievalrun"
)

// OpenAIEvalRun is the model entity for the OpenAIEvalRun schema.
type OpenAIEvalRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// TestType holds the value of the "test_type" field.
	TestType string `json:"test_type,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// ReasoningEffort holds the value of the "reasoning_effort" field.
	ReasoningEffort string `json:"reasoning_effort,omitempty"`
	// DataVersion holds the value of the "data_version" field.
	DataVersion string `json:"data_version,omitempty"`
	// BaselineVersion holds the value of the "baseline_version" field.
	BaselineVersion string `json:"baseline_version,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome map[string]interface{} `json:"outcome,omitempty"`
	// Samples holds the value of the "samples" field.
	Samples []map[string]interface{} `json:"samples,omitempty"`
	// RequestCount holds the value of the "request_count" field.
	RequestCount int `json:"request_count,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CostEstimateUsd holds the value of the "cost_estimate_usd" field.
	CostEstimateUsd *float64 `json:"cost_estimate_usd,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// TriggeredBy holds the value of the "triggered_by" field.
	TriggeredBy int64 `json:"triggered_by,omitempty"`
	// TriggerSource holds the value of the "trigger_source" field.
	TriggerSource string `json:"trigger_source,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RetentionUntil holds the value of the "retention_until" field.
	RetentionUntil time.Time `json:"retention_until,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIEvalRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaievalrun.FieldOutcome, openaievalrun.FieldSamples:
			values[i] = new([]byte)
		case openaievalrun.FieldCostEstimateUsd:
			values[i] = new(sql.NullFloat64)
		case openaievalrun.FieldID, openaievalrun.FieldAccountID, openaievalrun.FieldRequestCount, openaievalrun.FieldInputTokens, openaievalrun.FieldOutputTokens, openaievalrun.FieldDurationMs, openaievalrun.FieldTriggeredBy:
			values[i] = new(sql.NullInt64)
		case openaievalrun.FieldTestType, openaievalrun.FieldRequestedModel, openaievalrun.FieldUpstreamModel, openaievalrun.FieldReasoningEffort, openaievalrun.FieldDataVersion, openaievalrun.FieldBaselineVersion, openaievalrun.FieldStatus, openaievalrun.FieldTriggerSource, openaievalrun.FieldErrorCode:
			values[i] = new(sql.NullString)
		case openaievalrun.FieldStartedAt, openaievalrun.FieldFinishedAt, openaievalrun.FieldCreatedAt, openaievalrun.FieldRetentionUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIEvalRun fields.
func (_m *OpenAIEvalRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaievalrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaievalrun.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaievalrun.FieldTestType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field test_type", values[i])
			} else if value.Valid {
				_m.TestType = value.String
			}
		case openaievalrun.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case openaievalrun.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case openaievalrun.FieldReasoningEffort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_effort", values[i])
			} else if value.Valid {
				_m.ReasoningEffort = value.String
			}
		case openaievalrun.FieldDataVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_version", values[i])
			} else if value.Valid {
				_m.DataVersion = value.String
			}
		case openaievalrun.FieldBaselineVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field baseline_version", values[i])
			} else if value.Valid {
				_m.BaselineVersion = value.String
			}
		case openaievalrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case openaievalrun.FieldOutcome:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Outcome); err != nil {
					return fmt.Errorf("unmarshal field outcome: %w", err)
				}
			}
		case openaievalrun.FieldSamples:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field samples", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Samples); err != nil {
					return fmt.Errorf("unmarshal field samples: %w", err)
				}
			}
		case openaievalrun.FieldRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_count", values[i])
			} else if value.Valid {
				_m.RequestCount = int(value.Int64)
			}
		case openaievalrun.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case openaievalrun.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case openaievalrun.FieldCostEstimateUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_estimate_usd", values[i])
			} else if value.Valid {
				_m.CostEstimateUsd = new(float64)
				*_m.CostEstimateUsd = value.Float64
			}
		case openaievalrun.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case openaievalrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case openaievalrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case openaievalrun.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				_m.TriggeredBy = value.Int64
			}
		case openaievalrun.FieldTriggerSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_source", values[i])
			} else if value.Valid {
				_m.TriggerSource = value.String
			}
		case openaievalrun.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case openaievalrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaievalrun.FieldRetentionUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retention_until", values[i])
			} else if value.Valid {
				_m.RetentionUntil = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIEvalRun.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIEvalRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIEvalRun.
// Note that you need to call OpenAIEvalRun.Unwrap() before calling this method if this OpenAIEvalRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIEvalRun) Update() *OpenAIEvalRunUpdateOne {
	return NewOpenAIEvalRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIEvalRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIEvalRun) Unwrap() *OpenAIEvalRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIEvalRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIEvalRun) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIEvalRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("test_type=")
	builder.WriteString(_m.TestType)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("reasoning_effort=")
	builder.WriteString(_m.ReasoningEffort)
	builder.WriteString(", ")
	builder.WriteString("data_version=")
	builder.WriteString(_m.DataVersion)
	builder.WriteString(", ")
	builder.WriteString("baseline_version=")
	builder.WriteString(_m.BaselineVersion)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	builder.WriteString("samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.Samples))
	builder.WriteString(", ")
	builder.WriteString("request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestCount))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	if v := _m.CostEstimateUsd; v != nil {
		builder.WriteString("cost_estimate_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("triggered_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggeredBy))
	builder.WriteString(", ")
	builder.WriteString("trigger_source=")
	builder.WriteString(_m.TriggerSource)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("retention_until=")
	builder.WriteString(_m.RetentionUntil.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIEvalRuns is a parsable slice of OpenAIEvalRun.
type OpenAIEvalRuns []*OpenAIEvalRun
