// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaievalrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIEvalRunDelete is the builder for deleting a OpenAIEvalRun entity.
type OpenAIEvalRunDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIEvalRunMutation
}

// Where appends a list predicates to the OpenAIEvalRunDelete builder.
func (_d *OpenAIEvalRunDelete) Where(ps ...predicate.OpenAIEvalRun) *OpenAIEvalRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIEvalRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIEvalRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIEvalRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaievalrun.Table, sqlgraph.NewFieldSpec(openaievalrun.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIEvalRunDeleteOne is the builder for deleting a single OpenAIEvalRun entity.
type OpenAIEvalRunDeleteOne struct {
	_d *OpenAIEvalRunDelete
}

// Where appends a list predicates to the OpenAIEvalRunDelete builder.
func (_d *OpenAIEvalRunDeleteOne) Where(ps ...predicate.OpenAIEvalRun) *OpenAIEvalRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIEvalRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaievalrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIEvalRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
