// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaievalrun"
)

// OpenAIEvalRunCreate is the builder for creating a OpenAIEvalRun entity.
type OpenAIEvalRunCreate struct {
	config
	mutation *OpenAIEvalRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIEvalRunCreate) SetAccountID(v int64) *OpenAIEvalRunCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetTestType sets the "test_type" field.
func (_c *OpenAIEvalRunCreate) SetTestType(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetTestType(v)
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *OpenAIEvalRunCreate) SetRequestedModel(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *OpenAIEvalRunCreate) SetUpstreamModel(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableUpstreamModel(v *string) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_c *OpenAIEvalRunCreate) SetReasoningEffort(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetReasoningEffort(v)
	return _c
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableReasoningEffort(v *string) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetReasoningEffort(*v)
	}
	return _c
}

// SetDataVersion sets the "data_version" field.
func (_c *OpenAIEvalRunCreate) SetDataVersion(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetDataVersion(v)
	return _c
}

// SetBaselineVersion sets the "baseline_version" field.
func (_c *OpenAIEvalRunCreate) SetBaselineVersion(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetBaselineVersion(v)
	return _c
}

// SetNillableBaselineVersion sets the "baseline_version" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableBaselineVersion(v *string) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetBaselineVersion(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OpenAIEvalRunCreate) SetStatus(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *OpenAIEvalRunCreate) SetOutcome(v map[string]interface{}) *OpenAIEvalRunCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetSamples sets the "samples" field.
func (_c *OpenAIEvalRunCreate) SetSamples(v []map[string]interface{}) *OpenAIEvalRunCreate {
	_c.mutation.SetSamples(v)
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *OpenAIEvalRunCreate) SetRequestCount(v int) *OpenAIEvalRunCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableRequestCount(v *int) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetRequestCount(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *OpenAIEvalRunCreate) SetInputTokens(v int64) *OpenAIEvalRunCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableInputTokens(v *int64) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *OpenAIEvalRunCreate) SetOutputTokens(v int64) *OpenAIEvalRunCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableOutputTokens(v *int64) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (_c *OpenAIEvalRunCreate) SetCostEstimateUsd(v float64) *OpenAIEvalRunCreate {
	_c.mutation.SetCostEstimateUsd(v)
	return _c
}

// SetNillableCostEstimateUsd sets the "cost_estimate_usd" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableCostEstimateUsd(v *float64) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetCostEstimateUsd(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *OpenAIEvalRunCreate) SetDurationMs(v int64) *OpenAIEvalRunCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableDurationMs(v *int64) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *OpenAIEvalRunCreate) SetStartedAt(v time.Time) *OpenAIEvalRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *OpenAIEvalRunCreate) SetFinishedAt(v time.Time) *OpenAIEvalRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableFinishedAt(v *time.Time) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetTriggeredBy sets the "triggered_by" field.
func (_c *OpenAIEvalRunCreate) SetTriggeredBy(v int64) *OpenAIEvalRunCreate {
	_c.mutation.SetTriggeredBy(v)
	return _c
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableTriggeredBy(v *int64) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetTriggeredBy(*v)
	}
	return _c
}

// SetTriggerSource sets the "trigger_source" field.
func (_c *OpenAIEvalRunCreate) SetTriggerSource(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetTriggerSource(v)
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *OpenAIEvalRunCreate) SetErrorCode(v string) *OpenAIEvalRunCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableErrorCode(v *string) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIEvalRunCreate) SetCreatedAt(v time.Time) *OpenAIEvalRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIEvalRunCreate) SetNillableCreatedAt(v *time.Time) *OpenAIEvalRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRetentionUntil sets the "retention_until" field.
func (_c *OpenAIEvalRunCreate) SetRetentionUntil(v time.Time) *OpenAIEvalRunCreate {
	_c.mutation.SetRetentionUntil(v)
	return _c
}

// Mutation returns the OpenAIEvalRunMutation object of the builder.
func (_c *OpenAIEvalRunCreate) Mutation() *OpenAIEvalRunMutation {
	return _c.mutation
}

// Save creates the OpenAIEvalRun in the database.
func (_c *OpenAIEvalRunCreate) Save(ctx context.Context) (*OpenAIEvalRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIEvalRunCreate) SaveX(ctx context.Context) *OpenAIEvalRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIEvalRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIEvalRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIEvalRunCreate) defaults() {
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := openaievalrun.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		v := openaievalrun.DefaultReasoningEffort
		_c.mutation.SetReasoningEffort(v)
	}
	if _, ok := _c.mutation.BaselineVersion(); !ok {
		v := openaievalrun.DefaultBaselineVersion
		_c.mutation.SetBaselineVersion(v)
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		v := openaievalrun.DefaultOutcome
		_c.mutation.SetOutcome(v)
	}
	if _, ok := _c.mutation.Samples(); !ok {
		v := openaievalrun.DefaultSamples
		_c.mutation.SetSamples(v)
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		v := openaievalrun.DefaultRequestCount
		_c.mutation.SetRequestCount(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := openaievalrun.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := openaievalrun.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := openaievalrun.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		v := openaievalrun.DefaultTriggeredBy
		_c.mutation.SetTriggeredBy(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := openaievalrun.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaievalrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIEvalRunCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIEvalRun.account_id"`)}
	}
	if _, ok := _c.mutation.TestType(); !ok {
		return &ValidationError{Name: "test_type", err: errors.New(`ent: missing required field "OpenAIEvalRun.test_type"`)}
	}
	if v, ok := _c.mutation.TestType(); ok {
		if err := openaievalrun.TestTypeValidator(v); err != nil {
			return &ValidationError{Name: "test_type", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.test_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "OpenAIEvalRun.requested_model"`)}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := openaievalrun.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.requested_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "OpenAIEvalRun.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := openaievalrun.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		return &ValidationError{Name: "reasoning_effort", err: errors.New(`ent: missing required field "OpenAIEvalRun.reasoning_effort"`)}
	}
	if v, ok := _c.mutation.ReasoningEffort(); ok {
		if err := openaievalrun.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.reasoning_effort": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataVersion(); !ok {
		return &ValidationError{Name: "data_version", err: errors.New(`ent: missing required field "OpenAIEvalRun.data_version"`)}
	}
	if v, ok := _c.mutation.DataVersion(); ok {
		if err := openaievalrun.DataVersionValidator(v); err != nil {
			return &ValidationError{Name: "data_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.data_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaselineVersion(); !ok {
		return &ValidationError{Name: "baseline_version", err: errors.New(`ent: missing required field "OpenAIEvalRun.baseline_version"`)}
	}
	if v, ok := _c.mutation.BaselineVersion(); ok {
		if err := openaievalrun.BaselineVersionValidator(v); err != nil {
			return &ValidationError{Name: "baseline_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.baseline_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OpenAIEvalRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := openaievalrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "OpenAIEvalRun.outcome"`)}
	}
	if _, ok := _c.mutation.Samples(); !ok {
		return &ValidationError{Name: "samples", err: errors.New(`ent: missing required field "OpenAIEvalRun.samples"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "OpenAIEvalRun.request_count"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "OpenAIEvalRun.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "OpenAIEvalRun.output_tokens"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "OpenAIEvalRun.duration_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "OpenAIEvalRun.started_at"`)}
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		return &ValidationError{Name: "triggered_by", err: errors.New(`ent: missing required field "OpenAIEvalRun.triggered_by"`)}
	}
	if _, ok := _c.mutation.TriggerSource(); !ok {
		return &ValidationError{Name: "trigger_source", err: errors.New(`ent: missing required field "OpenAIEvalRun.trigger_source"`)}
	}
	if v, ok := _c.mutation.TriggerSource(); ok {
		if err := openaievalrun.TriggerSourceValidator(v); err != nil {
			return &ValidationError{Name: "trigger_source", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.trigger_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "OpenAIEvalRun.error_code"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := openaievalrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIEvalRun.created_at"`)}
	}
	if _, ok := _c.mutation.RetentionUntil(); !ok {
		return &ValidationError{Name: "retention_until", err: errors.New(`ent: missing required field "OpenAIEvalRun.retention_until"`)}
	}
	return nil
}

func (_c *OpenAIEvalRunCreate) sqlSave(ctx context.Context) (*OpenAIEvalRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIEvalRunCreate) createSpec() (*OpenAIEvalRun, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIEvalRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaievalrun.Table, sqlgraph.NewFieldSpec(openaievalrun.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaievalrun.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.TestType(); ok {
		_spec.SetField(openaievalrun.FieldTestType, field.TypeString, value)
		_node.TestType = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(openaievalrun.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(openaievalrun.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.ReasoningEffort(); ok {
		_spec.SetField(openaievalrun.FieldReasoningEffort, field.TypeString, value)
		_node.ReasoningEffort = value
	}
	if value, ok := _c.mutation.DataVersion(); ok {
		_spec.SetField(openaievalrun.FieldDataVersion, field.TypeString, value)
		_node.DataVersion = value
	}
	if value, ok := _c.mutation.BaselineVersion(); ok {
		_spec.SetField(openaievalrun.FieldBaselineVersion, field.TypeString, value)
		_node.BaselineVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(openaievalrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(openaievalrun.FieldOutcome, field.TypeJSON, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Samples(); ok {
		_spec.SetField(openaievalrun.FieldSamples, field.TypeJSON, value)
		_node.Samples = value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(openaievalrun.FieldRequestCount, field.TypeInt, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(openaievalrun.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(openaievalrun.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CostEstimateUsd(); ok {
		_spec.SetField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64, value)
		_node.CostEstimateUsd = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(openaievalrun.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(openaievalrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(openaievalrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.TriggeredBy(); ok {
		_spec.SetField(openaievalrun.FieldTriggeredBy, field.TypeInt64, value)
		_node.TriggeredBy = value
	}
	if value, ok := _c.mutation.TriggerSource(); ok {
		_spec.SetField(openaievalrun.FieldTriggerSource, field.TypeString, value)
		_node.TriggerSource = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(openaievalrun.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaievalrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RetentionUntil(); ok {
		_spec.SetField(openaievalrun.FieldRetentionUntil, field.TypeTime, value)
		_node.RetentionUntil = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIEvalRun.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIEvalRunUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIEvalRunCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIEvalRunUpsertOne {
	_c.conflict = opts
	return &OpenAIEvalRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIEvalRunCreate) OnConflictColumns(columns ...string) *OpenAIEvalRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIEvalRunUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIEvalRunUpsertOne is the builder for "upsert"-ing
	//  one OpenAIEvalRun node.
	OpenAIEvalRunUpsertOne struct {
		create *OpenAIEvalRunCreate
	}

	// OpenAIEvalRunUpsert is the "OnConflict" setter.
	OpenAIEvalRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *OpenAIEvalRunUpsert) SetAccountID(v int64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateAccountID() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIEvalRunUpsert) AddAccountID(v int64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldAccountID, v)
	return u
}

// SetTestType sets the "test_type" field.
func (u *OpenAIEvalRunUpsert) SetTestType(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldTestType, v)
	return u
}

// UpdateTestType sets the "test_type" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateTestType() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldTestType)
	return u
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIEvalRunUpsert) SetRequestedModel(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldRequestedModel, v)
	return u
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateRequestedModel() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldRequestedModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *OpenAIEvalRunUpsert) SetUpstreamModel(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateUpstreamModel() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldUpstreamModel)
	return u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *OpenAIEvalRunUpsert) SetReasoningEffort(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldReasoningEffort, v)
	return u
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateReasoningEffort() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldReasoningEffort)
	return u
}

// SetDataVersion sets the "data_version" field.
func (u *OpenAIEvalRunUpsert) SetDataVersion(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldDataVersion, v)
	return u
}

// UpdateDataVersion sets the "data_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateDataVersion() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldDataVersion)
	return u
}

// SetBaselineVersion sets the "baseline_version" field.
func (u *OpenAIEvalRunUpsert) SetBaselineVersion(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldBaselineVersion, v)
	return u
}

// UpdateBaselineVersion sets the "baseline_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateBaselineVersion() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldBaselineVersion)
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAIEvalRunUpsert) SetStatus(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateStatus() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldStatus)
	return u
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIEvalRunUpsert) SetOutcome(v map[string]interface{}) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldOutcome, v)
	return u
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateOutcome() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldOutcome)
	return u
}

// SetSamples sets the "samples" field.
func (u *OpenAIEvalRunUpsert) SetSamples(v []map[string]interface{}) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldSamples, v)
	return u
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateSamples() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldSamples)
	return u
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIEvalRunUpsert) SetRequestCount(v int) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldRequestCount, v)
	return u
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateRequestCount() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldRequestCount)
	return u
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIEvalRunUpsert) AddRequestCount(v int) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldRequestCount, v)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *OpenAIEvalRunUpsert) SetInputTokens(v int64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateInputTokens() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *OpenAIEvalRunUpsert) AddInputTokens(v int64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *OpenAIEvalRunUpsert) SetOutputTokens(v int64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateOutputTokens() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *OpenAIEvalRunUpsert) AddOutputTokens(v int64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldOutputTokens, v)
	return u
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsert) SetCostEstimateUsd(v float64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldCostEstimateUsd, v)
	return u
}

// UpdateCostEstimateUsd sets the "cost_estimate_usd" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateCostEstimateUsd() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldCostEstimateUsd)
	return u
}

// AddCostEstimateUsd adds v to the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsert) AddCostEstimateUsd(v float64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldCostEstimateUsd, v)
	return u
}

// ClearCostEstimateUsd clears the value of the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsert) ClearCostEstimateUsd() *OpenAIEvalRunUpsert {
	u.SetNull(openaievalrun.FieldCostEstimateUsd)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *OpenAIEvalRunUpsert) SetDurationMs(v int64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateDurationMs() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *OpenAIEvalRunUpsert) AddDurationMs(v int64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldDurationMs, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIEvalRunUpsert) SetStartedAt(v time.Time) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateStartedAt() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAIEvalRunUpsert) SetFinishedAt(v time.Time) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateFinishedAt() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAIEvalRunUpsert) ClearFinishedAt() *OpenAIEvalRunUpsert {
	u.SetNull(openaievalrun.FieldFinishedAt)
	return u
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *OpenAIEvalRunUpsert) SetTriggeredBy(v int64) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldTriggeredBy, v)
	return u
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateTriggeredBy() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldTriggeredBy)
	return u
}

// AddTriggeredBy adds v to the "triggered_by" field.
func (u *OpenAIEvalRunUpsert) AddTriggeredBy(v int64) *OpenAIEvalRunUpsert {
	u.Add(openaievalrun.FieldTriggeredBy, v)
	return u
}

// SetTriggerSource sets the "trigger_source" field.
func (u *OpenAIEvalRunUpsert) SetTriggerSource(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldTriggerSource, v)
	return u
}

// UpdateTriggerSource sets the "trigger_source" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateTriggerSource() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldTriggerSource)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAIEvalRunUpsert) SetErrorCode(v string) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateErrorCode() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldErrorCode)
	return u
}

// SetRetentionUntil sets the "retention_until" field.
func (u *OpenAIEvalRunUpsert) SetRetentionUntil(v time.Time) *OpenAIEvalRunUpsert {
	u.Set(openaievalrun.FieldRetentionUntil, v)
	return u
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsert) UpdateRetentionUntil() *OpenAIEvalRunUpsert {
	u.SetExcluded(openaievalrun.FieldRetentionUntil)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIEvalRunUpsertOne) UpdateNewValues() *OpenAIEvalRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaievalrun.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIEvalRunUpsertOne) Ignore() *OpenAIEvalRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIEvalRunUpsertOne) DoNothing() *OpenAIEvalRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIEvalRunCreate.OnConflict
// documentation for more info.
func (u *OpenAIEvalRunUpsertOne) Update(set func(*OpenAIEvalRunUpsert)) *OpenAIEvalRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIEvalRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIEvalRunUpsertOne) SetAccountID(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIEvalRunUpsertOne) AddAccountID(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateAccountID() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateAccountID()
	})
}

// SetTestType sets the "test_type" field.
func (u *OpenAIEvalRunUpsertOne) SetTestType(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTestType(v)
	})
}

// UpdateTestType sets the "test_type" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateTestType() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTestType()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIEvalRunUpsertOne) SetRequestedModel(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateRequestedModel() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *OpenAIEvalRunUpsertOne) SetUpstreamModel(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateUpstreamModel() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *OpenAIEvalRunUpsertOne) SetReasoningEffort(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateReasoningEffort() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetDataVersion sets the "data_version" field.
func (u *OpenAIEvalRunUpsertOne) SetDataVersion(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetDataVersion(v)
	})
}

// UpdateDataVersion sets the "data_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateDataVersion() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateDataVersion()
	})
}

// SetBaselineVersion sets the "baseline_version" field.
func (u *OpenAIEvalRunUpsertOne) SetBaselineVersion(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetBaselineVersion(v)
	})
}

// UpdateBaselineVersion sets the "baseline_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateBaselineVersion() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateBaselineVersion()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIEvalRunUpsertOne) SetStatus(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateStatus() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateStatus()
	})
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIEvalRunUpsertOne) SetOutcome(v map[string]interface{}) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateOutcome() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateOutcome()
	})
}

// SetSamples sets the "samples" field.
func (u *OpenAIEvalRunUpsertOne) SetSamples(v []map[string]interface{}) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetSamples(v)
	})
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateSamples() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateSamples()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIEvalRunUpsertOne) SetRequestCount(v int) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIEvalRunUpsertOne) AddRequestCount(v int) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateRequestCount() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRequestCount()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *OpenAIEvalRunUpsertOne) SetInputTokens(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *OpenAIEvalRunUpsertOne) AddInputTokens(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateInputTokens() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *OpenAIEvalRunUpsertOne) SetOutputTokens(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *OpenAIEvalRunUpsertOne) AddOutputTokens(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateOutputTokens() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertOne) SetCostEstimateUsd(v float64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetCostEstimateUsd(v)
	})
}

// AddCostEstimateUsd adds v to the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertOne) AddCostEstimateUsd(v float64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddCostEstimateUsd(v)
	})
}

// UpdateCostEstimateUsd sets the "cost_estimate_usd" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateCostEstimateUsd() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateCostEstimateUsd()
	})
}

// ClearCostEstimateUsd clears the value of the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertOne) ClearCostEstimateUsd() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.ClearCostEstimateUsd()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *OpenAIEvalRunUpsertOne) SetDurationMs(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *OpenAIEvalRunUpsertOne) AddDurationMs(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateDurationMs() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIEvalRunUpsertOne) SetStartedAt(v time.Time) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateStartedAt() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAIEvalRunUpsertOne) SetFinishedAt(v time.Time) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateFinishedAt() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAIEvalRunUpsertOne) ClearFinishedAt() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *OpenAIEvalRunUpsertOne) SetTriggeredBy(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTriggeredBy(v)
	})
}

// AddTriggeredBy adds v to the "triggered_by" field.
func (u *OpenAIEvalRunUpsertOne) AddTriggeredBy(v int64) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddTriggeredBy(v)
	})
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateTriggeredBy() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTriggeredBy()
	})
}

// SetTriggerSource sets the "trigger_source" field.
func (u *OpenAIEvalRunUpsertOne) SetTriggerSource(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTriggerSource(v)
	})
}

// UpdateTriggerSource sets the "trigger_source" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateTriggerSource() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTriggerSource()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAIEvalRunUpsertOne) SetErrorCode(v string) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateErrorCode() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateErrorCode()
	})
}

// SetRetentionUntil sets the "retention_until" field.
func (u *OpenAIEvalRunUpsertOne) SetRetentionUntil(v time.Time) *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRetentionUntil(v)
	})
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertOne) UpdateRetentionUntil() *OpenAIEvalRunUpsertOne {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRetentionUntil()
	})
}

// Exec executes the query.
func (u *OpenAIEvalRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIEvalRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIEvalRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIEvalRunUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIEvalRunUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIEvalRunCreateBulk is the builder for creating many OpenAIEvalRun entities in bulk.
type OpenAIEvalRunCreateBulk struct {
	config
	err      error
	builders []*OpenAIEvalRunCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIEvalRun entities in the database.
func (_c *OpenAIEvalRunCreateBulk) Save(ctx context.Context) ([]*OpenAIEvalRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIEvalRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIEvalRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIEvalRunCreateBulk) SaveX(ctx context.Context) []*OpenAIEvalRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIEvalRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIEvalRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIEvalRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIEvalRunUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIEvalRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIEvalRunUpsertBulk {
	_c.conflict = opts
	return &OpenAIEvalRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIEvalRunCreateBulk) OnConflictColumns(columns ...string) *OpenAIEvalRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIEvalRunUpsertBulk{
		create: _c,
	}
}

// OpenAIEvalRunUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIEvalRun nodes.
type OpenAIEvalRunUpsertBulk struct {
	create *OpenAIEvalRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIEvalRunUpsertBulk) UpdateNewValues() *OpenAIEvalRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaievalrun.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIEvalRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIEvalRunUpsertBulk) Ignore() *OpenAIEvalRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIEvalRunUpsertBulk) DoNothing() *OpenAIEvalRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIEvalRunCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIEvalRunUpsertBulk) Update(set func(*OpenAIEvalRunUpsert)) *OpenAIEvalRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIEvalRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIEvalRunUpsertBulk) SetAccountID(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIEvalRunUpsertBulk) AddAccountID(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateAccountID() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateAccountID()
	})
}

// SetTestType sets the "test_type" field.
func (u *OpenAIEvalRunUpsertBulk) SetTestType(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTestType(v)
	})
}

// UpdateTestType sets the "test_type" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateTestType() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTestType()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIEvalRunUpsertBulk) SetRequestedModel(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateRequestedModel() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *OpenAIEvalRunUpsertBulk) SetUpstreamModel(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateUpstreamModel() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *OpenAIEvalRunUpsertBulk) SetReasoningEffort(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateReasoningEffort() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetDataVersion sets the "data_version" field.
func (u *OpenAIEvalRunUpsertBulk) SetDataVersion(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetDataVersion(v)
	})
}

// UpdateDataVersion sets the "data_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateDataVersion() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateDataVersion()
	})
}

// SetBaselineVersion sets the "baseline_version" field.
func (u *OpenAIEvalRunUpsertBulk) SetBaselineVersion(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetBaselineVersion(v)
	})
}

// UpdateBaselineVersion sets the "baseline_version" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateBaselineVersion() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateBaselineVersion()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIEvalRunUpsertBulk) SetStatus(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateStatus() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateStatus()
	})
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIEvalRunUpsertBulk) SetOutcome(v map[string]interface{}) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateOutcome() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateOutcome()
	})
}

// SetSamples sets the "samples" field.
func (u *OpenAIEvalRunUpsertBulk) SetSamples(v []map[string]interface{}) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetSamples(v)
	})
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateSamples() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateSamples()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIEvalRunUpsertBulk) SetRequestCount(v int) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIEvalRunUpsertBulk) AddRequestCount(v int) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateRequestCount() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRequestCount()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *OpenAIEvalRunUpsertBulk) SetInputTokens(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *OpenAIEvalRunUpsertBulk) AddInputTokens(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateInputTokens() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *OpenAIEvalRunUpsertBulk) SetOutputTokens(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *OpenAIEvalRunUpsertBulk) AddOutputTokens(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateOutputTokens() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertBulk) SetCostEstimateUsd(v float64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetCostEstimateUsd(v)
	})
}

// AddCostEstimateUsd adds v to the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertBulk) AddCostEstimateUsd(v float64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddCostEstimateUsd(v)
	})
}

// UpdateCostEstimateUsd sets the "cost_estimate_usd" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateCostEstimateUsd() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateCostEstimateUsd()
	})
}

// ClearCostEstimateUsd clears the value of the "cost_estimate_usd" field.
func (u *OpenAIEvalRunUpsertBulk) ClearCostEstimateUsd() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.ClearCostEstimateUsd()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *OpenAIEvalRunUpsertBulk) SetDurationMs(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *OpenAIEvalRunUpsertBulk) AddDurationMs(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateDurationMs() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIEvalRunUpsertBulk) SetStartedAt(v time.Time) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateStartedAt() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAIEvalRunUpsertBulk) SetFinishedAt(v time.Time) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateFinishedAt() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAIEvalRunUpsertBulk) ClearFinishedAt() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *OpenAIEvalRunUpsertBulk) SetTriggeredBy(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTriggeredBy(v)
	})
}

// AddTriggeredBy adds v to the "triggered_by" field.
func (u *OpenAIEvalRunUpsertBulk) AddTriggeredBy(v int64) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.AddTriggeredBy(v)
	})
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateTriggeredBy() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTriggeredBy()
	})
}

// SetTriggerSource sets the "trigger_source" field.
func (u *OpenAIEvalRunUpsertBulk) SetTriggerSource(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetTriggerSource(v)
	})
}

// UpdateTriggerSource sets the "trigger_source" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateTriggerSource() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateTriggerSource()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAIEvalRunUpsertBulk) SetErrorCode(v string) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateErrorCode() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateErrorCode()
	})
}

// SetRetentionUntil sets the "retention_until" field.
func (u *OpenAIEvalRunUpsertBulk) SetRetentionUntil(v time.Time) *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.SetRetentionUntil(v)
	})
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *OpenAIEvalRunUpsertBulk) UpdateRetentionUntil() *OpenAIEvalRunUpsertBulk {
	return u.Update(func(s *OpenAIEvalRunUpsert) {
		s.UpdateRetentionUntil()
	})
}

// Exec executes the query.
func (u *OpenAIEvalRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIEvalRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIEvalRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIEvalRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
