// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaievalrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIEvalRunUpdate is the builder for updating OpenAIEvalRun entities.
type OpenAIEvalRunUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIEvalRunMutation
}

// Where appends a list predicates to the OpenAIEvalRunUpdate builder.
func (_u *OpenAIEvalRunUpdate) Where(ps ...predicate.OpenAIEvalRun) *OpenAIEvalRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIEvalRunUpdate) SetAccountID(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableAccountID(v *int64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIEvalRunUpdate) AddAccountID(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetTestType sets the "test_type" field.
func (_u *OpenAIEvalRunUpdate) SetTestType(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetTestType(v)
	return _u
}

// SetNillableTestType sets the "test_type" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableTestType(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetTestType(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *OpenAIEvalRunUpdate) SetRequestedModel(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableRequestedModel(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *OpenAIEvalRunUpdate) SetUpstreamModel(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableUpstreamModel(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *OpenAIEvalRunUpdate) SetReasoningEffort(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableReasoningEffort(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetDataVersion sets the "data_version" field.
func (_u *OpenAIEvalRunUpdate) SetDataVersion(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetDataVersion(v)
	return _u
}

// SetNillableDataVersion sets the "data_version" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableDataVersion(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetDataVersion(*v)
	}
	return _u
}

// SetBaselineVersion sets the "baseline_version" field.
func (_u *OpenAIEvalRunUpdate) SetBaselineVersion(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetBaselineVersion(v)
	return _u
}

// SetNillableBaselineVersion sets the "baseline_version" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableBaselineVersion(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetBaselineVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIEvalRunUpdate) SetStatus(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableStatus(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *OpenAIEvalRunUpdate) SetOutcome(v map[string]interface{}) *OpenAIEvalRunUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetSamples sets the "samples" field.
func (_u *OpenAIEvalRunUpdate) SetSamples(v []map[string]interface{}) *OpenAIEvalRunUpdate {
	_u.mutation.SetSamples(v)
	return _u
}

// AppendSamples appends value to the "samples" field.
func (_u *OpenAIEvalRunUpdate) AppendSamples(v []map[string]interface{}) *OpenAIEvalRunUpdate {
	_u.mutation.AppendSamples(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIEvalRunUpdate) SetRequestCount(v int) *OpenAIEvalRunUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableRequestCount(v *int) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIEvalRunUpdate) AddRequestCount(v int) *OpenAIEvalRunUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *OpenAIEvalRunUpdate) SetInputTokens(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableInputTokens(v *int64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *OpenAIEvalRunUpdate) AddInputTokens(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *OpenAIEvalRunUpdate) SetOutputTokens(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableOutputTokens(v *int64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *OpenAIEvalRunUpdate) AddOutputTokens(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdate) SetCostEstimateUsd(v float64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetCostEstimateUsd()
	_u.mutation.SetCostEstimateUsd(v)
	return _u
}

// SetNillableCostEstimateUsd sets the "cost_estimate_usd" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableCostEstimateUsd(v *float64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetCostEstimateUsd(*v)
	}
	return _u
}

// AddCostEstimateUsd adds value to the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdate) AddCostEstimateUsd(v float64) *OpenAIEvalRunUpdate {
	_u.mutation.AddCostEstimateUsd(v)
	return _u
}

// ClearCostEstimateUsd clears the value of the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdate) ClearCostEstimateUsd() *OpenAIEvalRunUpdate {
	_u.mutation.ClearCostEstimateUsd()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *OpenAIEvalRunUpdate) SetDurationMs(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableDurationMs(v *int64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *OpenAIEvalRunUpdate) AddDurationMs(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAIEvalRunUpdate) SetStartedAt(v time.Time) *OpenAIEvalRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableStartedAt(v *time.Time) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAIEvalRunUpdate) SetFinishedAt(v time.Time) *OpenAIEvalRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableFinishedAt(v *time.Time) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAIEvalRunUpdate) ClearFinishedAt() *OpenAIEvalRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *OpenAIEvalRunUpdate) SetTriggeredBy(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.ResetTriggeredBy()
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableTriggeredBy(v *int64) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// AddTriggeredBy adds value to the "triggered_by" field.
func (_u *OpenAIEvalRunUpdate) AddTriggeredBy(v int64) *OpenAIEvalRunUpdate {
	_u.mutation.AddTriggeredBy(v)
	return _u
}

// SetTriggerSource sets the "trigger_source" field.
func (_u *OpenAIEvalRunUpdate) SetTriggerSource(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetTriggerSource(v)
	return _u
}

// SetNillableTriggerSource sets the "trigger_source" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableTriggerSource(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetTriggerSource(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *OpenAIEvalRunUpdate) SetErrorCode(v string) *OpenAIEvalRunUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableErrorCode(v *string) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetRetentionUntil sets the "retention_until" field.
func (_u *OpenAIEvalRunUpdate) SetRetentionUntil(v time.Time) *OpenAIEvalRunUpdate {
	_u.mutation.SetRetentionUntil(v)
	return _u
}

// SetNillableRetentionUntil sets the "retention_until" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdate) SetNillableRetentionUntil(v *time.Time) *OpenAIEvalRunUpdate {
	if v != nil {
		_u.SetRetentionUntil(*v)
	}
	return _u
}

// Mutation returns the OpenAIEvalRunMutation object of the builder.
func (_u *OpenAIEvalRunUpdate) Mutation() *OpenAIEvalRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIEvalRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIEvalRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIEvalRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIEvalRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIEvalRunUpdate) check() error {
	if v, ok := _u.mutation.TestType(); ok {
		if err := openaievalrun.TestTypeValidator(v); err != nil {
			return &ValidationError{Name: "test_type", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.test_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := openaievalrun.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := openaievalrun.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := openaievalrun.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DataVersion(); ok {
		if err := openaievalrun.DataVersionValidator(v); err != nil {
			return &ValidationError{Name: "data_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.data_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaselineVersion(); ok {
		if err := openaievalrun.BaselineVersionValidator(v); err != nil {
			return &ValidationError{Name: "baseline_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.baseline_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaievalrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerSource(); ok {
		if err := openaievalrun.TriggerSourceValidator(v); err != nil {
			return &ValidationError{Name: "trigger_source", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.trigger_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := openaievalrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIEvalRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaievalrun.Table, openaievalrun.Columns, sqlgraph.NewFieldSpec(openaievalrun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaievalrun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaievalrun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TestType(); ok {
		_spec.SetField(openaievalrun.FieldTestType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(openaievalrun.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(openaievalrun.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(openaievalrun.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataVersion(); ok {
		_spec.SetField(openaievalrun.FieldDataVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaselineVersion(); ok {
		_spec.SetField(openaievalrun.FieldBaselineVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaievalrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(openaievalrun.FieldOutcome, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Samples(); ok {
		_spec.SetField(openaievalrun.FieldSamples, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSamples(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openaievalrun.FieldSamples, value)
		})
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaievalrun.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaievalrun.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(openaievalrun.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(openaievalrun.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(openaievalrun.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(openaievalrun.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostEstimateUsd(); ok {
		_spec.SetField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostEstimateUsd(); ok {
		_spec.AddField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64, value)
	}
	if _u.mutation.CostEstimateUsdCleared() {
		_spec.ClearField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(openaievalrun.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(openaievalrun.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openaievalrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openaievalrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openaievalrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(openaievalrun.FieldTriggeredBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggeredBy(); ok {
		_spec.AddField(openaievalrun.FieldTriggeredBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TriggerSource(); ok {
		_spec.SetField(openaievalrun.FieldTriggerSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(openaievalrun.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionUntil(); ok {
		_spec.SetField(openaievalrun.FieldRetentionUntil, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaievalrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIEvalRunUpdateOne is the builder for updating a single OpenAIEvalRun entity.
type OpenAIEvalRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIEvalRunMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIEvalRunUpdateOne) SetAccountID(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableAccountID(v *int64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIEvalRunUpdateOne) AddAccountID(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetTestType sets the "test_type" field.
func (_u *OpenAIEvalRunUpdateOne) SetTestType(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetTestType(v)
	return _u
}

// SetNillableTestType sets the "test_type" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableTestType(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetTestType(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *OpenAIEvalRunUpdateOne) SetRequestedModel(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableRequestedModel(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *OpenAIEvalRunUpdateOne) SetUpstreamModel(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableUpstreamModel(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *OpenAIEvalRunUpdateOne) SetReasoningEffort(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableReasoningEffort(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetDataVersion sets the "data_version" field.
func (_u *OpenAIEvalRunUpdateOne) SetDataVersion(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetDataVersion(v)
	return _u
}

// SetNillableDataVersion sets the "data_version" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableDataVersion(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetDataVersion(*v)
	}
	return _u
}

// SetBaselineVersion sets the "baseline_version" field.
func (_u *OpenAIEvalRunUpdateOne) SetBaselineVersion(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetBaselineVersion(v)
	return _u
}

// SetNillableBaselineVersion sets the "baseline_version" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableBaselineVersion(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetBaselineVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIEvalRunUpdateOne) SetStatus(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableStatus(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *OpenAIEvalRunUpdateOne) SetOutcome(v map[string]interface{}) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetSamples sets the "samples" field.
func (_u *OpenAIEvalRunUpdateOne) SetSamples(v []map[string]interface{}) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetSamples(v)
	return _u
}

// AppendSamples appends value to the "samples" field.
func (_u *OpenAIEvalRunUpdateOne) AppendSamples(v []map[string]interface{}) *OpenAIEvalRunUpdateOne {
	_u.mutation.AppendSamples(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIEvalRunUpdateOne) SetRequestCount(v int) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableRequestCount(v *int) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIEvalRunUpdateOne) AddRequestCount(v int) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *OpenAIEvalRunUpdateOne) SetInputTokens(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableInputTokens(v *int64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *OpenAIEvalRunUpdateOne) AddInputTokens(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *OpenAIEvalRunUpdateOne) SetOutputTokens(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableOutputTokens(v *int64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *OpenAIEvalRunUpdateOne) AddOutputTokens(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCostEstimateUsd sets the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdateOne) SetCostEstimateUsd(v float64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetCostEstimateUsd()
	_u.mutation.SetCostEstimateUsd(v)
	return _u
}

// SetNillableCostEstimateUsd sets the "cost_estimate_usd" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableCostEstimateUsd(v *float64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetCostEstimateUsd(*v)
	}
	return _u
}

// AddCostEstimateUsd adds value to the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdateOne) AddCostEstimateUsd(v float64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddCostEstimateUsd(v)
	return _u
}

// ClearCostEstimateUsd clears the value of the "cost_estimate_usd" field.
func (_u *OpenAIEvalRunUpdateOne) ClearCostEstimateUsd() *OpenAIEvalRunUpdateOne {
	_u.mutation.ClearCostEstimateUsd()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *OpenAIEvalRunUpdateOne) SetDurationMs(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableDurationMs(v *int64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *OpenAIEvalRunUpdateOne) AddDurationMs(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAIEvalRunUpdateOne) SetStartedAt(v time.Time) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableStartedAt(v *time.Time) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAIEvalRunUpdateOne) SetFinishedAt(v time.Time) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableFinishedAt(v *time.Time) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAIEvalRunUpdateOne) ClearFinishedAt() *OpenAIEvalRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *OpenAIEvalRunUpdateOne) SetTriggeredBy(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.ResetTriggeredBy()
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableTriggeredBy(v *int64) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// AddTriggeredBy adds value to the "triggered_by" field.
func (_u *OpenAIEvalRunUpdateOne) AddTriggeredBy(v int64) *OpenAIEvalRunUpdateOne {
	_u.mutation.AddTriggeredBy(v)
	return _u
}

// SetTriggerSource sets the "trigger_source" field.
func (_u *OpenAIEvalRunUpdateOne) SetTriggerSource(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetTriggerSource(v)
	return _u
}

// SetNillableTriggerSource sets the "trigger_source" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableTriggerSource(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetTriggerSource(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *OpenAIEvalRunUpdateOne) SetErrorCode(v string) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableErrorCode(v *string) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetRetentionUntil sets the "retention_until" field.
func (_u *OpenAIEvalRunUpdateOne) SetRetentionUntil(v time.Time) *OpenAIEvalRunUpdateOne {
	_u.mutation.SetRetentionUntil(v)
	return _u
}

// SetNillableRetentionUntil sets the "retention_until" field if the given value is not nil.
func (_u *OpenAIEvalRunUpdateOne) SetNillableRetentionUntil(v *time.Time) *OpenAIEvalRunUpdateOne {
	if v != nil {
		_u.SetRetentionUntil(*v)
	}
	return _u
}

// Mutation returns the OpenAIEvalRunMutation object of the builder.
func (_u *OpenAIEvalRunUpdateOne) Mutation() *OpenAIEvalRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIEvalRunUpdate builder.
func (_u *OpenAIEvalRunUpdateOne) Where(ps ...predicate.OpenAIEvalRun) *OpenAIEvalRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIEvalRunUpdateOne) Select(field string, fields ...string) *OpenAIEvalRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIEvalRun entity.
func (_u *OpenAIEvalRunUpdateOne) Save(ctx context.Context) (*OpenAIEvalRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIEvalRunUpdateOne) SaveX(ctx context.Context) *OpenAIEvalRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIEvalRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIEvalRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIEvalRunUpdateOne) check() error {
	if v, ok := _u.mutation.TestType(); ok {
		if err := openaievalrun.TestTypeValidator(v); err != nil {
			return &ValidationError{Name: "test_type", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.test_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := openaievalrun.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := openaievalrun.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := openaievalrun.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DataVersion(); ok {
		if err := openaievalrun.DataVersionValidator(v); err != nil {
			return &ValidationError{Name: "data_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.data_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaselineVersion(); ok {
		if err := openaievalrun.BaselineVersionValidator(v); err != nil {
			return &ValidationError{Name: "baseline_version", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.baseline_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaievalrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerSource(); ok {
		if err := openaievalrun.TriggerSourceValidator(v); err != nil {
			return &ValidationError{Name: "trigger_source", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.trigger_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := openaievalrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAIEvalRun.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIEvalRunUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIEvalRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaievalrun.Table, openaievalrun.Columns, sqlgraph.NewFieldSpec(openaievalrun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIEvalRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaievalrun.FieldID)
		for _, f := range fields {
			if !openaievalrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaievalrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaievalrun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaievalrun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TestType(); ok {
		_spec.SetField(openaievalrun.FieldTestType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(openaievalrun.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(openaievalrun.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(openaievalrun.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataVersion(); ok {
		_spec.SetField(openaievalrun.FieldDataVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaselineVersion(); ok {
		_spec.SetField(openaievalrun.FieldBaselineVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaievalrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(openaievalrun.FieldOutcome, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Samples(); ok {
		_spec.SetField(openaievalrun.FieldSamples, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSamples(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openaievalrun.FieldSamples, value)
		})
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaievalrun.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaievalrun.FieldRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(openaievalrun.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(openaievalrun.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(openaievalrun.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(openaievalrun.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostEstimateUsd(); ok {
		_spec.SetField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostEstimateUsd(); ok {
		_spec.AddField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64, value)
	}
	if _u.mutation.CostEstimateUsdCleared() {
		_spec.ClearField(openaievalrun.FieldCostEstimateUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(openaievalrun.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(openaievalrun.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openaievalrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openaievalrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openaievalrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(openaievalrun.FieldTriggeredBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggeredBy(); ok {
		_spec.AddField(openaievalrun.FieldTriggeredBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TriggerSource(); ok {
		_spec.SetField(openaievalrun.FieldTriggerSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(openaievalrun.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionUntil(); ok {
		_spec.SetField(openaievalrun.FieldRetentionUntil, field.TypeTime, value)
	}
	_node = &OpenAIEvalRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaievalrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
